//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grafy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("grafy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language: English.
        /// </summary>
        internal static string chart_name {
            get {
                return ResourceManager.GetString("chart_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is in incorrect format. Please use the format {yyyyMMdd}..
        /// </summary>
        internal static string ChartError_BadDateFormat {
            get {
                return ResourceManager.GetString("ChartError_BadDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is in incorrect format. Please use the format {cz|en}-{variable}-{start date}-{end date}.ashx..
        /// </summary>
        internal static string ChartError_BadQueryStringFormat {
            get {
                return ResourceManager.GetString("ChartError_BadQueryStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ChartError_Heading {
            get {
                return ResourceManager.GetString("ChartError_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no data. Please try a different period..
        /// </summary>
        internal static string ChartError_NoDataForPeriod {
            get {
                return ResourceManager.GetString("ChartError_NoDataForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the language is not supported.\n Please use {en} (English) or {cz} (Czech)..
        /// </summary>
        internal static string ChartError_NoLanguage {
            get {
                return ResourceManager.GetString("ChartError_NoLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the station {0} does not exist.\n Please try a different station number..
        /// </summary>
        internal static string ChartError_NoStation {
            get {
                return ResourceManager.GetString("ChartError_NoStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the station {0} doesn&apos;t measure {1}.\nPlease try a different station..
        /// </summary>
        internal static string ChartError_NoStationVariable {
            get {
                return ResourceManager.GetString("ChartError_NoStationVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable  is not supported.\n Please try &apos;pcp&apos; (precipitation), &apos;flw&apos; (discharge), &apos; wtr&apos; (water stage) or &apos;snw&apos; (snow)..
        /// </summary>
        internal static string ChartError_NoVariable {
            get {
                return ResourceManager.GetString("ChartError_NoVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an unknown error ocurred when plotting the graph..
        /// </summary>
        internal static string ChartError_UnknownError {
            get {
                return ResourceManager.GetString("ChartError_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source:.
        /// </summary>
        internal static string data_source {
            get {
                return ResourceManager.GetString("data_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no data.\n Please select a different period..
        /// </summary>
        internal static string no_data_message {
            get {
                return ResourceManager.GetString("no_data_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precipitation (mm/day).
        /// </summary>
        internal static string precip_day_axis {
            get {
                return ResourceManager.GetString("precip_day_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precipitation (mm/h).
        /// </summary>
        internal static string precip_hour_axis {
            get {
                return ResourceManager.GetString("precip_hour_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precipitation.
        /// </summary>
        internal static string precip_label {
            get {
                return ResourceManager.GetString("precip_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precipitation sum (mm).
        /// </summary>
        internal static string precip_sum_axis {
            get {
                return ResourceManager.GetString("precip_sum_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precipitation sum.
        /// </summary>
        internal static string precip_sum_label {
            get {
                return ResourceManager.GetString("precip_sum_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datatype &lt;- c(&quot;POSIXct&quot;)
        ///names(datatype) &lt;- c(&quot;datum&quot;)
        ///url &lt;- &apos;http://hydrodata.info/api/values?st=169&amp;v=vodstav,prutok&amp;od=2013-05-20&amp;do=2013-06-30&apos;;
        ///data &lt;- read.table(url, sep=&apos;\t&apos;, header=TRUE,colClasses=datatype)
        ///plot(data$vodstav, data$prutok)
        ///plot(data$datum, data$prutok,type=&quot;l&quot;, col=&quot;blue&quot;, lwd=2)
        ///
        ///url2 &lt;- url &lt;- &apos;http://hydrodata.info/api/values?st=169&amp;v=prutok&amp;od=2013-05-20&amp;do=2013-06-30&amp;step=h&apos;;
        ///data2 &lt;- read.table(url, sep=&apos;\t&apos;, header=TRUE,colClasses=datatype)
        ///lines(data2$datum, data2$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_r_script {
            get {
                return ResourceManager.GetString("sample_r_script", resourceCulture);
            }
        }
    }
}
