UPDATE plaveninycz.stations SET st_name2 = 'SINDELOVA-OBORA' WHERE st_id = 806;
UPDATE plaveninycz.stations SET st_name2 = 'MARIANSKE LAZNE' WHERE st_id = 26;
UPDATE plaveninycz.stations SET st_name2 = 'PRIMDA' WHERE st_id = 24;
UPDATE plaveninycz.stations SET st_name2 = 'NOVA VES V HORACH' WHERE st_id = 218;
UPDATE plaveninycz.stations SET st_name2 = 'HOJSOVA STRAZ' WHERE st_id = 531;
UPDATE plaveninycz.stations SET st_name2 = 'CHURANOV' WHERE st_id = 23;
UPDATE plaveninycz.stations SET st_name2 = 'MILESOVKA' WHERE st_id = 47;
UPDATE plaveninycz.stations SET st_name2 = 'NADEJKOV' WHERE st_id = 27;
UPDATE plaveninycz.stations SET st_name2 = 'CERNA V POSUMAVI' WHERE st_id = 25;
UPDATE plaveninycz.stations SET st_name2 = 'BEDRICHOV' WHERE st_id = 219;
UPDATE plaveninycz.stations SET st_name2 = 'DESNA-SOUS' WHERE st_id = 220;
UPDATE plaveninycz.stations SET st_name2 = 'NOVY RYCHNOV' WHERE st_id = 221;
UPDATE plaveninycz.stations SET st_name2 = 'LUCNI BOUDA' WHERE st_id = 801;
UPDATE plaveninycz.stations SET st_name2 = 'SPI. MLYN-LABSKA B.' WHERE st_id = 1;
UPDATE plaveninycz.stations SET st_name2 = 'PEC POD SNEZKOU' WHERE st_id = 2;
UPDATE plaveninycz.stations SET st_name2 = 'POLOM-SEDLONOV' WHERE st_id = 528;
UPDATE plaveninycz.stations SET st_name2 = 'DESTNE' WHERE st_id = 4;
UPDATE plaveninycz.stations SET st_name2 = 'ROKYTNICE V ORL.HO.' WHERE st_id = 5;
UPDATE plaveninycz.stations SET st_name2 = 'SVRATOUCH' WHERE st_id = 3;
UPDATE plaveninycz.stations SET st_name2 = 'PAPRSEK' WHERE st_id = 222;
UPDATE plaveninycz.stations SET st_name2 = 'PROTIVANOV' WHERE st_id = 62;
UPDATE plaveninycz.stations SET st_name2 = 'SERAK' WHERE st_id = 223;
UPDATE plaveninycz.stations SET st_name2 = 'CERVENA U LIBAVE' WHERE st_id = 53;
UPDATE plaveninycz.stations SET st_name = 'Červená u Libavé' WHERE st_id = 53;
UPDATE plaveninycz.stations SET st_name2 = 'LYSA HORA' WHERE st_id = 52;
UPDATE plaveninycz.stations SET st_name2 = 'FICHTELBERG' WHERE st_id = 227;
UPDATE plaveninycz.stations SET st_name2 = 'CINOVEC' WHERE st_id = 228;
UPDATE plaveninycz.stations SET st_name2 = 'VELKY JAVOR' WHERE st_id = 229;
UPDATE plaveninycz.stations SET st_name2 = 'SNEZKA' WHERE st_id = 230;