//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatisticsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatisticsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.StatisticsResource", typeof(StatisticsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string discharge_max {
            get {
                return ResourceManager.GetString("discharge_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string discharge_min {
            get {
                return ResourceManager.GetString("discharge_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent available data.
        /// </summary>
        internal static string percent_available {
            get {
                return ResourceManager.GetString("percent_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days with precipitation.
        /// </summary>
        internal static string precip_count {
            get {
                return ResourceManager.GetString("precip_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum daily precipitation.
        /// </summary>
        internal static string precip_max {
            get {
                return ResourceManager.GetString("precip_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total precipitation.
        /// </summary>
        internal static string precip_sum {
            get {
                return ResourceManager.GetString("precip_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days with snow.
        /// </summary>
        internal static string snow_count {
            get {
                return ResourceManager.GetString("snow_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum snow cover.
        /// </summary>
        internal static string snow_max {
            get {
                return ResourceManager.GetString("snow_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string stage_max {
            get {
                return ResourceManager.GetString("stage_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string stage_min {
            get {
                return ResourceManager.GetString("stage_min", resourceCulture);
            }
        }
    }
}
