update stations set division_name='hk' where st_id=1
update stations set division_name='hk' where st_id=4
update stations set division_name='hk' where st_id=5
update stations set division_name='hk' where st_id=6
update stations set division_name='hk' where st_id=7
update stations set division_name='hk' where st_id=8
update stations set division_name='hk' where st_id=11
update stations set division_name='hk' where st_id=12
update stations set division_name='ul' where st_id=13
update stations set division_name='hk' where st_id=14
update stations set division_name='hk' where st_id=16
update stations set division_name='ul' where st_id=17
update stations set division_name='ul' where st_id=18
update stations set division_name='5' where st_id=19
update stations set division_name='hk' where st_id=21
update stations set division_name='cb' where st_id=25
update stations set division_name='cb' where st_id=27
update stations set division_name='cb' where st_id=28
update stations set division_name='cb' where st_id=31
update stations set division_name='pl' where st_id=32
update stations set division_name='cb' where st_id=35
update stations set division_name='cb' where st_id=36
update stations set division_name='pl' where st_id=37
update stations set division_name='cb' where st_id=38
update stations set division_name='cb' where st_id=39
update stations set division_name='pl' where st_id=40
update stations set division_name='pl' where st_id=43
update stations set division_name='pl' where st_id=44
update stations set division_name='ul' where st_id=47
update stations set division_name='ul' where st_id=50
update stations set division_name='os' where st_id=54
update stations set division_name='os' where st_id=55
update stations set division_name='os' where st_id=56
update stations set division_name='os' where st_id=57
update stations set division_name='os' where st_id=58
update stations set division_name='os' where st_id=59
update stations set division_name='os' where st_id=61
update stations set division_name='br' where st_id=62
update stations set division_name='os' where st_id=64
update stations set division_name='os' where st_id=65
update stations set division_name='os' where st_id=66
update stations set division_name='os' where st_id=67
update stations set division_name='br' where st_id=68
update stations set division_name='br' where st_id=69
update stations set division_name='br' where st_id=70
update stations set division_name='br' where st_id=71
update stations set division_name='os' where st_id=72
update stations set division_name='br' where st_id=74
update stations set division_name='br' where st_id=75
update stations set division_name='br' where st_id=77
update stations set division_name='br' where st_id=79
update stations set division_name='br' where st_id=83
update stations set division_name='br' where st_id=84
update stations set division_name='br' where st_id=86
update stations set division_name='ul' where st_id=218
update stations set division_name='ul' where st_id=219
update stations set division_name='pr' where st_id=220
update stations set division_name='pr' where st_id=221
update stations set division_name='7' where st_id=222
update stations set division_name='hk' where st_id=242
update stations set division_name='hk' where st_id=243
update stations set division_name='pl' where st_id=251
update stations set division_name='7' where st_id=252
update stations set division_name='7' where st_id=255
update stations set division_name='5' where st_id=335
update stations set division_name='cb' where st_id=527
update stations set division_name='pl' where st_id=531
update stations set division_name='pr' where st_id=532
update stations set division_name='pl' where st_id=533
update stations set division_name='hk' where st_id=534
update stations set division_name='hk' where st_id=538
update stations set division_name='br' where st_id=541
update stations set division_name='pr' where st_id=544
update stations set division_name='pr' where st_id=545
update stations set division_name='pr' where st_id=546
update stations set division_name='pr' where st_id=547
update stations set division_name='pr' where st_id=548
update stations set division_name='pr' where st_id=552
update stations set division_name='pr' where st_id=554
update stations set division_name='1' where st_id=555
update stations set division_name='7' where st_id=635
update stations set division_name='7' where st_id=639
update stations set division_name='hk' where st_id=648
update stations set division_name='5' where st_id=649
update stations set division_name='ul' where st_id=656
update stations set division_name='hk' where st_id=662
update stations set division_name='4' where st_id=665
update stations set division_name='5' where st_id=666
update stations set division_name='5' where st_id=667
update stations set division_name='2' where st_id=679
update stations set division_name='ul' where st_id=749
update stations set division_name='hk' where st_id=801
update stations set division_name='3' where st_id=841
update stations set division_name='3' where st_id=842
update stations set division_name='ul' where st_id=843
update stations set division_name='7' where st_id=846
update stations set division_name='6' where st_id=848
update stations set division_name='os' where st_id=849
update stations set division_name='pl' where st_id=851
update stations set division_name='2' where st_id=855
update stations set division_name='br' where st_id=856
update stations set division_name='2' where st_id=860
update stations set division_name='cb' where st_id=861
update stations set division_name='cb' where st_id=863
update stations set division_name='pr' where st_id=865
update stations set division_name='pr' where st_id=870
update stations set division_name='br' where st_id=871
update stations set division_name='7' where st_id=874
update stations set division_name='pr' where st_id=875
update stations set division_name='2' where st_id=876
update stations set division_name='2' where st_id=878
update stations set division_name='3' where st_id=879
update stations set division_name='ul' where st_id=881
update stations set division_name='7' where st_id=885
update stations set division_name='4' where st_id=886
update stations set division_name='5' where st_id=888
update stations set division_name='pl' where st_id=889
update stations set division_name='pr' where st_id=890
update stations set division_name='6' where st_id=894
update stations set division_name='6' where st_id=899
update stations set division_name='7' where st_id=900
update stations set division_name='2' where st_id=901
update stations set division_name='pr' where st_id=902
update stations set division_name='br' where st_id=903
update stations set division_name='2' where st_id=926
update stations set division_name='7' where st_id=928
update stations set division_name='br' where st_id=930
update stations set division_name='1' where st_id=931
update stations set division_name='6' where st_id=932
update stations set division_name='7' where st_id=934
update stations set division_name='7' where st_id=935
update stations set division_name='6' where st_id=936
update stations set division_name='4' where st_id=939
update stations set division_name='7' where st_id=940
update stations set division_name='7' where st_id=941
update stations set division_name='1' where st_id=942
update stations set division_name='4' where st_id=944
update stations set division_name='' where st_id=991
update stations set division_name='cb' where st_id=994
update stations set division_name='7' where st_id=995
update stations set division_name='4' where st_id=996
update stations set division_name='7' where st_id=998
update stations set division_name='br' where st_id=999
update stations set division_name='6' where st_id=1000
update stations set division_name='7' where st_id=1002
update stations set division_name='7' where st_id=1003
update stations set division_name='3' where st_id=1004
update stations set division_name='2' where st_id=1005
update stations set division_name='3' where st_id=1006