update stations set st_name='Daleké Dušníky', st_uri='kocaba/daleke_dusniky' where st_id=1012;
update stations set st_name='Průhonice', st_uri='dobrejovicky/pruhonice' where st_id=1014;
update stations set st_name='Libouchec', st_uri='libouchec' where st_id=1015;
update stations set st_name='Zaječice', st_uri='lezak/zajecice' where st_id=1016;
update stations set st_name='Mezisvětí', st_uri='chrudimka/mezisveti' where st_id=1017;
update stations set st_name='Brumov', st_uri='brumov' where st_id=1018;
update stations set st_name='Popov', st_uri='popov' where st_id=1019;
update stations set st_name='Bojkovice', st_uri='bojkovice' where st_id=1020;
update stations set st_name='Ludkovice', st_uri='ludkovice' where st_id=1021;
update stations set st_name='VD Luhačovice', st_uri='vd_luhacovice' where st_id=1022;
update stations set st_name='Přelouč', st_uri='prelouc' where st_id=1023;
update stations set st_name='Kolín', st_uri='kolin' where st_id=1024;
update stations set st_name='Srnojedy', st_uri='srnojedy' where st_id=1025;
update stations set st_name='KS Pardubice', st_uri='ks_pardubice' where st_id=1026;
update stations set st_name='Předměřice nad Labem', st_uri='predmerice_nad_labem' where st_id=1027;
update stations set st_name='Smiřice', st_uri='smirice' where st_id=1028;

update stations set st_name='Rejvíz', st_uri='rejviz' where st_id=1029;
update stations set st_name='Biskupská Kupa', st_uri='biskupska_kupa' where st_id=1030;
update stations set st_name='Anenský Vrch', st_uri='anensky_vrch' where st_id=1031;
update stations set st_name='Radynia', st_uri='radynia' where st_id=1032;
update stations set st_name='Mezina', st_uri='mezina' where st_id=1033;
update stations set st_name='Jelenice', st_uri='jelenice' where st_id=1034;
update stations set st_name='Kletné', st_uri='kletne' where st_id=1035;
update stations set st_name='Fulnek', st_uri='fulnek' where st_id=1036;
update stations set st_name='Jezdecká', st_uri='jezdecka' where st_id=1037;
update stations set st_name='Valašská Senice', st_uri='valasska_senice' where st_id=1038;
update stations set st_name='Rýmařov ČHMÚ', st_uri='rymarov_chmu' where st_id=1039;
update stations set st_name='Město Albrechtice', st_uri='mesto_albrechtice' where st_id=1040;
update stations set st_name='Jablonec nad Nisou', st_uri='jablonec_nad_nisou' where st_id=1041;
update stations set st_name='Jihlava - Hruškové Dvory', st_uri='jihlava_hruskove-dvory' where st_id=1042;
update stations set st_name='Staré Hutě', st_uri='stare_hute' where st_id=1043;
update stations set st_name='Svatý Jan', st_uri='svaty_jan' where st_id=1044;
update stations set st_name='Vlašim', st_uri='vlasim' where st_id=1045;
update stations set st_name='Voznice', st_uri='voznice' where st_id=1046;
update stations set st_name='Netvořice', st_uri='netvorice' where st_id=1047;
update stations set st_name='Horšovský Týn', st_uri='horsovsky_tyn' where st_id=1048;
update stations set st_name='Mašťov', st_uri='mastov' where st_id=1049;
update stations set st_name='Hrob - Křižanov', st_uri='hrob-krizanov' where st_id=1050;
update stations set st_name='Mořkov', st_uri='morkov' where st_id=1051;
update stations set st_name='Nezvěstice', st_uri='nezvestice' where st_id=1052;
update stations set st_name='Mrzky', st_uri='mrzky' where st_id=1053;
update stations set st_name='Bojkovice ČHMÚ', st_uri='bojkovice_chmu' where st_id=1054;
update stations set st_name='Staré Sedlo - Darmyšl', st_uri='darmysl' where st_id=1055;
update stations set st_name='Čáslav, Nové Město', st_uri='caslav-nove_mesto' where st_id=1056;
update stations set st_name='Dřevohostice', st_uri='drevohostice' where st_id=1057;
update stations set st_name='Kralupy nad Vltavou', st_uri='kralupy' where st_id=1058;
update stations set st_name='Praha - Klementinum', st_uri='praha-klementinum' where st_id=1059;
update stations set st_name='Karlova Studánka', st_uri='karlova_studanka' where st_id=1060;
update stations set st_name='Stříbro ČHMÚ', st_uri='stribro_chmu' where st_id=1061;
update stations set st_name='Hliniště', st_uri='hliniste' where st_id=1062;
update stations set st_name='Volary', st_uri='volary' where st_id=1063;
update stations set st_name='Hošťálková', st_uri='hostalkova' where st_id=1064;
update stations set st_name='Jizerka - rašeliniště', st_uri='jizerka-raseliniste' where st_id=1065;
update stations set st_name='Zlaté Hory', st_uri='zlate_hory' where st_id=1066;
update stations set st_name='Hanušovice', st_uri='hanusovice' where st_id=1067;
update stations set st_name='Slezská Harta ČHMÚ', st_uri='slezska_harta_chmu' where st_id=1068;
update stations set st_name='Rokytská Slať', st_uri='rokytska_slat' where st_id=1069;
update stations set st_name='Březník', st_uri='breznik' where st_id=1070;
update stations set st_name='Kvilda - Jezerní Slať', st_uri='kvilda-jezerni_slat' where st_id=1071;
update stations set st_name='Arnoštov', st_uri='arnostov' where st_id=1072;
update stations set st_name='Dolní Dvořiště', st_uri='dolni_dvoriste' where st_id=1073;
update stations set st_name='Haugschlag', st_uri='haugschlag' where st_id=1074;
update stations set st_name='Karlstift', st_uri='karlstift' where st_id=1075;
update stations set st_name='Líčov', st_uri='licov' where st_id=1076;
update stations set st_name='Limbach', st_uri='limbach' where st_id=1077;
update stations set st_name='Novosedly', st_uri='novosedly' where st_id=1078;
update stations set st_name='Pilař - Majdalena', st_uri='pilar-majdalena' where st_id=1079;
update stations set st_name='Písek', st_uri='pisek' where st_id=1080;
update stations set st_name='Pořešín', st_uri='poresin' where st_id=1081;
update stations set st_name='Pořešín', st_uri='poresin' where st_id=1082;
update stations set st_name='Spálenec', st_uri='spalenec' where st_id=1083;
update stations set st_name='Šumavské Hoštice', st_uri='sumavske_hostice' where st_id=1084;
update stations set st_name='Tučapy', st_uri='tucapy' where st_id=1085;
update stations set st_name='Třebanice', st_uri='trebanice' where st_id=1086;
update stations set st_name='Zátoň', st_uri='zaton' where st_id=1087;
update stations set st_name='Korce', st_uri='korce' where st_id=1088;
update stations set st_name='Samšín', st_uri='samsin' where st_id=1089;
update stations set st_name='Ústí (Želivka)', st_uri='usti_zelivka' where st_id=1090;
update stations set st_name='Strašice', st_uri='strasice' where st_id=1091;
update stations set st_name='Lesná', st_uri='lesna' where st_id=1092;
update stations set st_name='Branka', st_uri='branka' where st_id=1093;
update stations set st_name='Bravantice', st_uri='bravantice' where st_id=1094;
update stations set st_name='Bartošovice', st_uri='bartosovice' where st_id=1095;
update stations set st_name='Děhylov', st_uri='dehylov' where st_id=1097;
update stations set st_name='Istebná', st_uri='istebna' where st_id=1098;
update stations set st_name='Branice', st_uri='branice' where st_id=1099;
update stations set st_name='Kozlovice', st_uri='kozlovice' where st_id=1100;
update stations set st_name='Tichá', st_uri='ticha' where st_id=1101;
update stations set st_name='Vlčovice', st_uri='vlcovice' where st_id=1102;
update stations set st_name='Velký Javorník', st_uri='velky_javornik' where st_id=1103;
update stations set st_name='Věřňovice', st_uri='vernovice' where st_id=1104;
update stations set st_name='Kotař', st_uri='kotar' where st_id=1105;
update stations set st_name='Babí Hora', st_uri='babi_hora' where st_id=1106;
update stations set st_name='Slavíč - chata', st_uri='slavic-chata' where st_id=1107;
update stations set st_name='Čeladná', st_uri='celadna' where st_id=1108;
update stations set st_name='Vyšní Lhoty', st_uri='vysni_lhoty' where st_id=1109;
update stations set st_name='Kojetín', st_uri='kojetin' where st_id=1110;
update stations set st_name='Štramberk', st_uri='stramberk' where st_id=1111;
update stations set st_name='Slatina', st_uri='slatina' where st_id=1112;
update stations set st_name='Nový Dvůr', st_uri='novy_dvur' where st_id=1113;
update stations set st_name='Senomaty', st_uri='senomaty' where st_id=1115;
update stations set st_name='Jindřichov', st_uri='jindrichov' where st_id=1114;
update stations set st_name='Petrovice', st_uri='petrovice' where st_id=1116;
update stations set st_name='Unhošť', st_uri='unhost' where st_id=1117;
update stations set st_name='Ruda', st_uri='ruda' where st_id=1118;
update stations set st_name='Kladno', st_uri='kladno' where st_id=1119;
update stations set st_name='Vysoký Újezd', st_uri='vysoky_ujezd' where st_id=1120;
update stations set st_name='Kytín', st_uri='kytin' where st_id=1121;
update stations set st_name='Střezimíř', st_uri='strezimir' where st_id=1122;
update stations set st_name='Benešov', st_uri='benesov' where st_id=1123;
update stations set st_name='Milevsko', st_uri='milevsko' where st_id=1124;
update stations set st_name='Halámky', st_uri='halamky' where st_id=1125;
update stations set st_name='Nová Pec', st_uri='nova_pec' where st_id=1126;
update stations set st_name='Bezděkov pod Třemšínem', st_uri='bezdekov_pod_tremsinem' where st_id=1127;
update stations set st_name='Míšov', st_uri='misov' where st_id=1128;
update stations set st_name='Plzeň - Radčice', st_uri='plzen-radcice' where st_id=1129;
update stations set st_name='Ješetice', st_uri='jesetice' where st_id=1130;
update stations set st_name='Praha - Velká Chuchle', st_uri='praha-velka_chuchle' where st_id=1131;
update stations set st_name='Praha - Prosek', st_uri='praha-prosek' where st_id=1132;
update stations set st_name='Praha - Bohdalec', st_uri='praha-bohdalec' where st_id=1133;
update stations set st_name='Praha - Strahov', st_uri='praha-strahov' where st_id=1134;
update stations set st_name='Deštnice', st_uri='destnice' where st_id=1135;
update stations set st_name='Pikov', st_uri='pikov' where st_id=1136;
update stations set st_name='Tábor meteo', st_uri='tabor_meteo' where st_id=1137;
update stations set st_name='Frymburk', st_uri='frymburk' where st_id=1138;
update stations set st_name='Český Krumlov meteo', st_uri='cesky_krumlov_meteo' where st_id=1139;
update stations set st_name='Veselí nad Lužnicí', st_uri='veseli_nad_luznici' where st_id=1140;
update stations set st_name='Čechtice', st_uri='cechtice' where st_id=1141;
update stations set st_name='Počátky meteo', st_uri='pocatky_meteo' where st_id=1142;
update stations set st_name='Řevničov', st_uri='revnicov' where st_id=1143;
update stations set st_name='Konstantinovy Lázně meteo', st_uri='konstantinovy_lazne_meteo' where st_id=1144;
update stations set st_name='Plzeň - Košutka', st_uri='plzen-kosutka' where st_id=1145;
update stations set st_name='Slapy', st_uri='slapy' where st_id=1146;
update stations set st_name='Svatý Jan meteo', st_uri='svaty_jan_meteo' where st_id=1147;
update stations set st_name='Volary meteo', st_uri='volary_meteo' where st_id=1148;
update stations set st_name='Kubova Huť', st_uri='kubova_hut' where st_id=1149;
update stations set st_name='České Budějovice meteo', st_uri='ceske_budejovice_meteo' where st_id=1150;
update stations set st_name='Kojetice', st_uri='kojetice' where st_id=1151;
update stations set st_name='Boseň - Mužský', st_uri='bosen-muzsky' where st_id=1152;
update stations set st_name='Bystřice nad Pernštejnem', st_uri='bystrice_nad_pernstejnem' where st_id=1153;
update stations set st_name='Bystřice pod Hostýnem', st_uri='bystrice_pod_hostynem' where st_id=1154;
update stations set st_name='Děčín ČHMÚ', st_uri='decin_chmu' where st_id=1155;
update stations set st_name='Domažlice', st_uri='domazlice' where st_id=1156;
update stations set st_name='Frýdek - Místek', st_uri='frydek-mistek' where st_id=1157;
update stations set st_name='Hluboká nad Vltavou', st_uri='hluboka_nad_vltavou' where st_id=1158;
update stations set st_name='Hrušová', st_uri='hrusova' where st_id=1159;
update stations set st_name='Chlum u Třeboně', st_uri='chlum_u_trebone' where st_id=1160;
update stations set st_name='Chrastava', st_uri='chrastava' where st_id=1161;
update stations set st_name='Chudenice', st_uri='chudenice' where st_id=1162;
update stations set st_name='Luisino Údolí', st_uri='luisino_udoli' where st_id=1163;
update stations set st_name='Milešov', st_uri='milesov' where st_id=1164;
update stations set st_name='Olešnice', st_uri='olesnice' where st_id=1165;
update stations set st_name='Počátky ČHMÚ', st_uri='pocatky_chmu' where st_id=1166;
update stations set st_name='Praha - Břevnov', st_uri='praha-brevnov' where st_id=1167;
update stations set st_name='Slatiny, Milíčeves', st_uri='slatiny-miliceves' where st_id=1168;
update stations set st_name='Smědava', st_uri='smedava' where st_id=1169;
update stations set st_name='Sněžník', st_uri='sneznik' where st_id=1170;
update stations set st_name='Trutnov', st_uri='trutnov' where st_id=1171;
update stations set st_name='Zlonice', st_uri='zlonice' where st_id=1173;
update stations set st_name='Turnov ČHMÚ', st_uri='turnov_chmu' where st_id=1172;

update stations set st_name='Malé Kyšice - Poteplí', st_uri='lodenice/potepli' where st_id=1249;
update stations set st_name='Košátky', st_uri='kosatecky/kosatky' where st_id=1250;
update stations set st_name='Želízy', st_uri='libechovka/zelizy' where st_id=1251;
update stations set st_name='Dolní Bukovina', st_uri='zabrdka/dolni_bukovina' where st_id=1252;
update stations set st_name='Velký Rečkov', st_uri='bela/velky_reckov' where st_id=1253;
update stations set st_name='Mladá Boleslav', st_uri='klenice/mlada_boleslav' where st_id=1254;
update stations set st_name='Mezihoří', st_uri='trebuvka/mezihori' where st_id=1255;
update stations set st_name='Chornice', st_uri='jevicka/chornice' where st_id=1256;
update stations set st_name='Jaroměřice', st_uri='usobrnsky_potok/jaromerice' where st_id=1257;
update stations set st_name='Zděchov', st_uri='zdechovka/zdechov' where st_id=1258;
update stations set st_name='Hranice', st_uri='velicka/hranice' where st_id=1259;
update stations set st_name='Netolice', st_uri='bezdrevsky/netolice' where st_id=1260;
update stations set st_name='Lékařova Lhota', st_uri='bezdrevsky/lekarova_lhota' where st_id=1261;
update stations set st_name='Soběsuky', st_uri='hloucela/sobesuky' where st_id=1262;
update stations set st_name='Koryčany nad přehradou', st_uri='kyjovka/korycany_nad_prehradou' where st_id=1263;
update stations set st_name='VD Koryčany', st_uri='kyjovka/vd_korycany' where st_id=1264;
update stations set st_name='Rýmařov', st_uri='podolsky/rymarov' where st_id=1265;
update stations set st_name='Sedlnice', st_uri='sedlnice/sedlnice' where st_id=1266;
update stations set st_name='Tichá', st_uri='tichavka/ticha' where st_id=1267;
update stations set st_name='Jeseník nad Odrou', st_uri='luha/jesenik_nad_odrou' where st_id=1268;
update stations set st_name='Jablunkov - Lomná', st_uri='lomna/jablunkov' where st_id=1269;
update stations set st_name='Polanka nad Odrou', st_uri='polancice/polanka_nad_odrou' where st_id=1270;
update stations set st_name='Smilovice', st_uri='ropicanka/smilovice' where st_id=1271;
update stations set st_name='Baška', st_uri='bastice/baska' where st_id=1272;
update stations set st_name='Palkovice', st_uri='olesna/palkovice' where st_id=1273;
update stations set st_name='Olešná', st_uri='olesna/olesna' where st_id=1274;
update stations set st_name='Stará Bělá', st_uri='starobelsky_potok/stara_bela' where st_id=1275;
update stations set st_name='Frýdek - Místek', st_uri='ostravice/frydek-mistek' where st_id=1276;
update stations set st_name='Raškovice', st_uri='mohelnice/raskovice' where st_id=1277;
update stations set st_name='Vyšní Lhoty', st_uri='moravka/vysni_lhoty' where st_id=1278;
update stations set st_name='Morávka', st_uri='moravka/moravka' where st_id=1279;
update stations set st_name='Těrlicko', st_uri='stonavka/terlicko' where st_id=1280;
update stations set st_name='Žermanice', st_uri='lucina/zermanice' where st_id=1281;
update stations set st_name='Bludovice', st_uri='lucina/bludovice' where st_id=1282;
update stations set st_name='Šance', st_uri='ostravice/sance' where st_id=1283;
update stations set st_name='Smikov', st_uri='chotysanka/smikov' where st_id=1284;
update stations set st_name='Břevnice', st_uri='brevnicky_potok/brevnice' where st_id=1285;
update stations set st_name='Hořepník', st_uri='trnava/horepnik' where st_id=1286;
update stations set st_name='Slavníkovice', st_uri='polenka/slavnikovice' where st_id=1287;
update stations set st_name='Hadrava', st_uri='chodska_uhlava/hadrava' where st_id=1288;
update stations set st_name='VD Husinec', st_uri='blanice/vd_husinec' where st_id=1289;
update stations set st_name='Kamenice nad Lipou', st_uri='kamenice/kamenice_nad_lipou' where st_id=1290;
update stations set st_name='Gopprechts', st_uri='dracice/gopprechts' where st_id=1291;
update stations set st_name='Altmanns', st_uri='skremelice/altmanns' where st_id=1292;
update stations set st_name='Heidenreichstein', st_uri='romavsky_potok/heidenreichstein' where st_id=1293;


